name: Release

on:
  workflow_run:
    workflows:
      - Lint and Test
    branches:
      - main
    types:
      - completed

jobs:
  create-release:
    runs-on: ubuntu-latest

    permissions:
        contents: write      # Allows pushing commits and creating tags
        actions: write       # Allows creating releases
        checks: write
        deployments: write
        id-token: write
        issues: write
        discussions: write
        packages: write
        pages: write
        pull-requests: write
        repository-projects: write
        security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Choose the node version
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install
      
      - name: Set Git config
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      - name: Update Version & changelog
        run: npm run release --verbose

      - name: Push changes and tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for release
        run: |
          git push --follow-tags origin main

      - name: Get Latest Tag
        id: latest-tag
        run: echo "latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

      - name: Print Latest Tag
        run: echo "The latest tag is ${{ env.latest_tag }}"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          prerelease: false
          title: "Release ${{ env.latest_tag }}"